server:
  port: 9700
  max-http-header-size: 756000
  jetty:
    threads:
      min: 100
      max: 3000
      idle-timeout: 10000
    connection-idle-timeout: 10000
    accesslog:
      enabled: true

spring:
  application:
    name: spring-boot-camel-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: saber66
    password: AdminSaber66
    hikari:
      max-lifetime: 10000
      idle-timeout: 10000
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true

service:
  api:
    camel:
      base-path: /services/camel/${spring.application.name}
    springboot:
      base-path: /services/springboot/${spring.application.name}
  swagger:
    path: /spring-camel-docs/v2/api-docs
    version: 'version1.1.0-1402/08/15'
    camel:
      title: 'spring boot camel test'
    springboot:
      title: 'spring boot test'
      description: 'spring boot test'

camel:
  springboot:
    name: 'spring-boot-camel-test'
  servlet:
    mapping:
      context-path: ${service.api.camel.base-path}/*
  component:
    http:
      connect-timeout: 10000
      connection-request-timeout: 30000
      connection-time-to-live: 30000
      socket-timeout: 30000
      connections-per-route: 300
      max-total-connections: 3000
  dataformat:
    jackson:
      auto-discover-object-mapper: true
      pretty-print: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    urls:
      - name: 'spring camel test'
        url: ${service.api.camel.base-path}${service.swagger.path}
      - name: 'spring boot test'
        url: ${springdoc.api-docs.path}

  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuators/${spring.application.name}